# -*- coding: utf-8 -*-
"""0718_colab_ex1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M7IkHKyrrv2r0CnYXbQ0J5WYFytRYsq5

구글 코랩 사용법
1. 구글 크롬 로그인
2. 구글에 코랩 검색

**연습장**

* 텍스트의 사용법은 마크다운 문법을 참고할 것  
https://hongsii.github.io/2017/06/01/How-to-Write-with-Markdown/

자주 사용될 문법

* '\<br/>'을 사용하면 enter로 사용됨
* 문장의 뒤에 띄어쓰기 두번을 하면 줄바꿈이 됨.

Germini -> AI  
ex)파이썬 문서 포맷팅 예제 10개 만들어줘

<br/>
아래의 코드는, Germini를 이용하여 생성한 예제이다.
"""

name = "Alice"
age = 30
print(f"이름: {name}, 나이: {age}")

x = 1
y = 2

def add(x, y):
  """두 숫자를 더합니다.

  Args:
    x: 첫 번째 숫자.
    y: 두 번째 숫자.

  Returns:
    두 숫자의 합.
  """
  return x + y

result = add(x,y)
print(result)