server:
  port: 9092
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: c##scott
    password: tiger
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update #개발 중에는 update나 create, 배포시에는 none으로 권장
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect
  #        physical_naming_strategy: com.kosmo.jpa.demo.util.CustomPhysicalNamingStrategy
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace


